nsp_article_add_new_article:
    path:     /ajout
    defaults: { _controller: NSPArticleBundle:Article:addNewArticle }

nsp_article_add_champs_article:
    path:     /ajouter/{id}
    defaults: { _controller: NSPArticleBundle:Article:addChampsArticle }

nsp_article_add_validation:
    path:     /validation/{id}
    defaults: { _controller: NSPArticleBundle:Article:addValidation }

nsp_article_article:
    path:     /{titreArticle}
    defaults: {_controller: NSPArticleBundle:Article:viewArticle }
    # requirements: {titreArticle: "[a-zA-Z0-9]{3,25}"}
