nsp_article_addNewArticle:
    path:     /ajout
    defaults: { _controller: NSPArticleBundle:Article:addNewArticle }

nsp_article_addChampsArticle:
    path:     /ajout/champs/{id}.{photo1}.{photo2}.{photo3}.{photo4}.{photo5}.{photo6}
    defaults: { _controller: NSPArticleBundle:Article:addChampsArticle }

nsp_article_addValidation:
    path:     /validation/{id}
    defaults: { _controller: NSPArticleBundle:Article:addValidation }

nsp_article_article:
    path:     /{titreArticle}
    defaults: {_controller: NSPArticleBundle:Article:viewArticle }
    # requirements: {titreArticle: "[a-zA-Z0-9]{3,25}"}
