nsp_article_add:
    path:     /ajoutArticle
    defaults: { _controller: NSPArticleBundle:Article:add }

nsp_article_article:
    path:     /{titreArticle}
    defaults: {_controller: NSPArticleBundle:Article:viewArticle }
    # requirements: {titreArticle: "[a-zA-Z0-9]{3,25}"}
