nsp_article_new_article:
    path:     /ajout
    defaults: { _controller: NSPArticleBundle:Article:addNewArticle }

nsp_article_add_champs_article:
    path:     /nouveau/{id}
    defaults: { _controller: NSPArticleBundle:Article:addChampsArticle }

nsp_article_article:
    path:     /article/{id}
    defaults: {_controller: NSPArticleBundle:Article:viewArticle }
    # requirements: {titreArticle: "[a-zA-Z0-9]{3,25}"}
