<?php

namespace NSP\ArticleBundle\Entity;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{

	public function findComments($article)
	{
	  $qb = $this->createQueryBuilder('c');

	  $qb
	    ->where('c.article = :article')
	    ->setParameter('article', $article)
	    ->orderBy('c.id', 'DESC')
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}

	public function findAllByDate()
	{
	  $qb = $this->createQueryBuilder('c');

	  $qb->orderBy('c.id', 'DESC');

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}

}
