<?php

namespace NSP\ArticleBundle\Entity;

use Doctrine\ORM\QueryBuilder;

/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByName($nameRubrique)
	{
	  $qb = $this->createQueryBuilder('r');

	  $qb
	    ->where('r.nom = :nom')
	    ->setParameter('nom', $nameRubrique)
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}


}
