<?php

namespace NSP\ArticleBundle\Entity;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUserName($username)
	{
	  $qb = $this->createQueryBuilder('u');

	  $qb
	    ->where('u.username = :username')
	    ->setParameter('username', $username)
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}
}
