<?php

namespace NSP\ArticleBundle\Entity;

/**
 * UtilisateurCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurCommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
