<?php

namespace NSP\ArticleBundle\Entity;

/**
 * UtilisateurArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurArticleRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findNotes($article)
	{
	  $qb = $this->createQueryBuilder('n');

	  $qb
	    ->where('n.article = :article')
	    ->setParameter('article', $article)
	    ->orderBy('n.id', 'DESC')
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}
    
    	public function findNote($article)
	{
	  $qb = $this->createQueryBuilder('n');

	  $qb
        ->select("avg(n.note)")
        ->where('n.article = :article')
	    ->setParameter('article', $article);

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}
    
        public function findNotebyUser($article, $utilisateur)
	{
	  $qb = $this->createQueryBuilder('n');

	  $qb
	    ->where('n.article = :article')
        ->andWhere('n.utilisateur = :utilisateur')
	    ->setParameter('article', $article)
	    ->setParameter('utilisateur', $utilisateur)
	    ->orderBy('n.id', 'DESC')
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}
    
}
