nsp_back_homepage:
    path:     /back
    defaults: { _controller: NSPBackBundle:Back:viewHomeBack }

nsp_back_moderation:
    path:     /back/moderation
    defaults: { _controller: NSPBackBundle:Back:viewModerationBack }

nsp_back_administration:
    path:     /back/administration
    defaults: { _controller: NSPBackBundle:Back:viewAdministrationBack }

nsp_back_statistiques:
    path:     /back/statistiques
    defaults: { _controller: NSPBackBundle:Back:viewStatistiquesBack }

nsp_back_publier:
    path:     /back/moderation/publication/{id}
    defaults: { _controller: NSPBackBundle:Back:publier }

nsp_back_supprimer_article:
    path:     /back/administration/supression/{id}
    defaults: { _controller: NSPBackBundle:Back:supprimerArticle }

nsp_back_supprimer_commentaire:
    path:     /back/administration/supression/commentaire/{id}
    defaults: { _controller: NSPBackBundle:Back:supprimerCommentaire }