nsp_interface_homepage:
    path:     /
    defaults: { _controller: NSPInterfaceBundle:Interface:index }

nsp_interface_rubrique:
    path:     /{rubrique}
    defaults: 
        _controller: NSPInterfaceBundle:Interface:viewRubrique
    requirements:
        rubrique: "^(Campus|BonPlan|LifeStyle|Culture|Evenement)$"

nsp_interface_contact:
    path:     /contact
    defaults: { _controller: NSPInterfaceBundle:Interface:contact }