nsp_interface_homepage:
    path:     /
    defaults: { _controller: NSPInterfaceBundle:Interface:index }

nsp_interface_rubrique:
    path:     /rubrique/{rubrique}
    defaults: 
        _controller: NSPInterfaceBundle:Interface:viewRubrique
    requirements:
        rubrique: "^(Campus|BonPlan|LifeStyle|Culture|Evenement)$"

nsp_interface_contact:
    path:     /contact
    defaults: { _controller: NSPInterfaceBundle:Interface:contact }

nsp_interface_remerciements:
    path:     /remerciements
    defaults: { _controller: NSPInterfaceBundle:Interface:remerciement }

nsp_interface_a_propos:
    path:     /information
    defaults: { _controller: NSPInterfaceBundle:Interface:info }

nsp_interface_mentions_legales:
    path:     /mentions
    defaults: { _controller: NSPInterfaceBundle:Interface:mentionslgl}