nsp_back_user:
    resource: "@NSPBackUserBundle/Resources/config/routing.yml"
    prefix:   /

nsp_back:
    resource: "@NSPBackBundle/Resources/config/routing.yml"
    prefix:   /

nsp_interface:
    resource: "@NSPInterfaceBundle/Resources/config/routing.yml"
    prefix:   /

nsp_article:
    resource: "@NSPArticleBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

