nsp_interface:
    resource: "@NSPInterfaceBundle/Resources/config/routing.yml"
    prefix:   /

nsp_article:
    resource: "@NSPArticleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

